#BookStore Configuration
#Sun Jan 04 14:16:45 MSK 2026
jdbc=jdbc\:postgresql\://localhost\:5432/db_java_senla
jdbcDriver=org.postgresql.Driver
numberOfMonth=6
password=postgres
user=postgres
warehouseFunction=true
