<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example</groupId>
    <artifactId>servlet-app</artifactId>
    <version>1.0.0-SNAPHOT</version>
    <packaging>war</packaging>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <final.war.name>HelloServlet</final.war.name>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <!-- Servlet API -->
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>4.0.1</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <finalName>${final.war.name}</finalName>
        <pluginManagement>

            <plugins>
                <plugin>
                    <!--Плагин компилирует JAva код в байт-код-->
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.11.0</version>
                    <configuration>
                        <source>${maven.compiler.source}</source><!--версия джавы исходного кода-->
                        <target>${maven.compiler.target}</target><!--версия джавы JVM - для которой создается байт-код-->
                    </configuration>
                </plugin>
                <!--Плагин создает war-->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-war-plugin</artifactId>
                    <version>3.4.0</version>
                    <configuration>
                        <!-- Исключаем библиотеки с scope provided из WAR -->
                        <packagingExcludes>WEB-INF/lib/*.jar</packagingExcludes>
                        <failOnMissingWebXml>false</failOnMissingWebXml>
                    </configuration>
                </plugin>

                <!--Плагин копирует war в tomcat-->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-antrun-plugin</artifactId>
                    <version>3.1.0</version>
                    <executions>
                        <execution>
                            <id>deploy-to-tomcat</id>
                            <phase>install</phase>
                            <goals>
                                <goal>run</goal>
                            </goals>
                            <configuration>
                                <target>
                                    <copy file="${project.build.directory}/${project.build.finalName}.war"
                                          tofile="/var/lib/tomcat9/webapps/${project.build.finalName}.war"
                                          verbose="true"/>
                                    <echo message="WAR файл скопирован в Tomcat!"/>
                                </target>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>

            </plugins>

        </pluginManagement>
    </build>
</project>